[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace  STM32F407VG with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip STM32F401RE"

[target.thumbv7em-none-eabihf]
rustflags = ["-C", "link-arg=-Tlink.x"]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"
